# Generated by Django 3.0.5 on 2021-02-12 05:52

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.TextField()),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('dob', models.DateTimeField()),
                ('phoneNum', models.IntegerField()),
            ],
        ),
    ]
